### ISSUE TITLE
[cosmos-proxy] The proxy crashes when no list of public user spaces is configured

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cosmos#191]
A check about the emptyness of the list, even if no empty list is configured at all, must be added.

This could be generalized to all the configuration paramenters.

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cosmos/pull/199

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cosmos/pull/202

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cosmos/pull/202
