### ISSUE TITLE
[cosmos-hive-auth-provider] Create an OAuth2-based custom authentication provider for Hive

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cosmos#57]
Custom authentication providers can be created for Hive while extending the [`PasswordAuthenticationProvider`](http://hive.apache.org/javadocs/r0.12.0/api/org/apache/hive/service/auth/PasswdAuthenticationProvider.html) interface. This is a password-oriented interface, but custom implementations may give new semantics to the concept of password; specifically, an OAuth2 token may be passed instead.

**Comment by frbattid** [comment]
This could also be an OAuth2-based Thrift proxy.

**Comment by frbattid** [comment]
<h1>Pluggable authentication</h1>

Pluggable authentication allows you to provide a custom authentication provider for HiveServer2.

To enable pluggable authentication:

    Set the following properties in /etc/hive/conf/hive-site.xml:

    <property>
      <name>hive.server2.authentication</name>
      <value>CUSTOM</value>
      <description>Client authentication types.
      NONE: no authentication check
      LDAP: LDAP/AD based authentication
      KERBEROS: Kerberos/GSSAPI authentication
      CUSTOM: Custom authentication provider
      (Use with property hive.server2.custom.authentication.class)
      </description>
    </property>

    <property>
      <name>hive.server2.custom.authentication.class</name>
      <value>pluggable-auth-class-name</value>
      <description>
      Custom authentication class. Used when property
      'hive.server2.authentication' is set to 'CUSTOM'. Provided class
      must be a proper implementation of the interface
      org.apache.hive.service.auth.PasswdAuthenticationProvider. HiveServer2
      will call its Authenticate(user, passed) method to authenticate requests.
      The implementation may optionally extend the Hadoop's
      org.apache.hadoop.conf.Configured class to grab Hive's Configuration object.
      </description>
    </property>

Make the class available in the CLASSPATH of HiveServer2.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cosmos/pull/144

**Comment by long1208** [comment]
hi ,Make the class available in the CLASSPATH of HiveServer2 ,could you tell me " CLASSPATH of HiveServer2" is what?
